// protos/time.proto
//
// This file defines the gRPC service and messages for the time streaming service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: protos/time.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing no parameters.
type TimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	mi := &file_protos_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_protos_time_proto_rawDescGZIP(), []int{0}
}

// The response message containing the current time.
type TimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTime   string                 `protobuf:"bytes,1,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	mi := &file_protos_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_protos_time_proto_rawDescGZIP(), []int{1}
}

func (x *TimeResponse) GetCurrentTime() string {
	if x != nil {
		return x.CurrentTime
	}
	return ""
}

var File_protos_time_proto protoreflect.FileDescriptor

const file_protos_time_proto_rawDesc = "" +
	"\n" +
	"\x11protos/time.proto\x12\x04time\"\r\n" +
	"\vTimeRequest\"1\n" +
	"\fTimeResponse\x12!\n" +
	"\fcurrent_time\x18\x01 \x01(\tR\vcurrentTime2F\n" +
	"\vTimeService\x127\n" +
	"\n" +
	"StreamTime\x12\x11.time.TimeRequest\x1a\x12.time.TimeResponse\"\x000\x01B\x1aZ\x18your_project_name/protosb\x06proto3"

var (
	file_protos_time_proto_rawDescOnce sync.Once
	file_protos_time_proto_rawDescData []byte
)

func file_protos_time_proto_rawDescGZIP() []byte {
	file_protos_time_proto_rawDescOnce.Do(func() {
		file_protos_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_time_proto_rawDesc), len(file_protos_time_proto_rawDesc)))
	})
	return file_protos_time_proto_rawDescData
}

var file_protos_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_time_proto_goTypes = []any{
	(*TimeRequest)(nil),  // 0: time.TimeRequest
	(*TimeResponse)(nil), // 1: time.TimeResponse
}
var file_protos_time_proto_depIdxs = []int32{
	0, // 0: time.TimeService.StreamTime:input_type -> time.TimeRequest
	1, // 1: time.TimeService.StreamTime:output_type -> time.TimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_time_proto_init() }
func file_protos_time_proto_init() {
	if File_protos_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_time_proto_rawDesc), len(file_protos_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_time_proto_goTypes,
		DependencyIndexes: file_protos_time_proto_depIdxs,
		MessageInfos:      file_protos_time_proto_msgTypes,
	}.Build()
	File_protos_time_proto = out.File
	file_protos_time_proto_goTypes = nil
	file_protos_time_proto_depIdxs = nil
}
